[cmake] add cmake build script to build OpenThread
This PR adds a bash script to compile the platform that supports cmake.

Usage Examples:
    ./script/cmake-build cc1352
    ./script/cmake-build posix -DOT_MAC_FILTER=on

diff --git a/script/check-arm-build-cmake b/script/check-arm-build-cmake
--- a/script/check-arm-build-cmake
+++ b/script/check-arm-build-cmake
@@ -33,8 +33,22 @@ readonly OT_SRCDIR="$(pwd)"
 readonly OT_BUILDDIR="$OT_SRCDIR/build"
 
 readonly OT_COMMON_OPTIONS=(
-    "-DOT_COMPILE_WARNING_AS_ERROR=ON"
+    "-DOT_COMPILE_WARNING_AS_ERROR=on"
 )
+
+readonly OT_BASIC_CHECK_OPTIONS=(
+    "-DOT_COMMISSIONER=on"
+    "-DOT_DHCP6_CLIENT=on"
+    "-DOT_DHCP6_SERVER=on"
+    "-DOT_DNS_CLIENT=on"
+    "-DOT_JOINER=on"
+    "-DOT_SLAAC=on"
+)
+
+die() {
+    echo " *** ERROR:  $*"
+    exit 1
+}
 
 reset_source()
 {
@@ -43,160 +57,68 @@ reset_source()
 
 build_cc1352()
 {
-    local options=("${OT_COMMON_OPTIONS[@]}")
-
-    options+=(
-        "-DOT_PLATFORM=cc1352"
-        "-DCMAKE_TOOLCHAIN_FILE=examples/platforms/cc1352/arm-none-eabi.cmake"
-        "-DOT_COMMISSIONER=on"
-        "-DOT_DHCP6_CLIENT=on"
-        "-DOT_DHCP6_SERVER=on"
-        "-DOT_DNS_CLIENT=on"
-        "-DOT_JOINER=on"
-        "-DOT_SLAAC=on"
-        "-DCMAKE_BUILD_TYPE=Release"
-    )
+    local options=("${OT_COMMON_OPTIONS[@]}"
+                   "${OT_BASIC_CHECK_OPTIONS[@]}")
 
     reset_source
-    mkdir -p "$OT_BUILDDIR"
-    cd "$OT_BUILDDIR"
-    cmake -GNinja "${options[@]}" ..
-    ninja
-    cd "$OT_SRCDIR"
+    "$(dirname "$0")"/cmake-build cc1352 "${options[@]}"
 }
 
 build_cc2538()
 {
-    local options=("${OT_COMMON_OPTIONS[@]}")
-
-    options+=(
-        "-DOT_PLATFORM=cc2538"
-        "-DCMAKE_TOOLCHAIN_FILE=examples/platforms/cc2538/arm-none-eabi.cmake"
-    )
+    local options=("${OT_COMMON_OPTIONS[@]}"
+                   "${OT_BASIC_CHECK_OPTIONS[@]}")
 
     reset_source
-    mkdir -p "$OT_BUILDDIR"
-    cd "$OT_BUILDDIR"
-    cmake -GNinja "${options[@]}" ..
-    ninja
-    cd "$OT_SRCDIR"
+    "$(dirname "$0")"/cmake-build cc2538 "${options[@]}"
 }
 
 build_cc2650()
 {
-    local options=("${OT_COMMON_OPTIONS[@]}")
-
-    options+=(
-        "-DOT_PLATFORM=cc2650"
-        "-DCMAKE_TOOLCHAIN_FILE=examples/platforms/cc2650/arm-none-eabi.cmake"
-        "-DCMAKE_BUILD_TYPE=Release"
-    )
-
     reset_source
-    mkdir -p "$OT_BUILDDIR"
-    cd "$OT_BUILDDIR"
-    cmake -GNinja "${options[@]}" ..
-    ninja ot-cli-mtd ot-ncp-mtd
-    cd "$OT_SRCDIR"
+    "$(dirname "$0")"/cmake-build cc2650 "${OT_COMMON_OPTIONS[@]}"
 }
 
 build_cc2652()
 {
-    local options=("${OT_COMMON_OPTIONS[@]}")
-
-    options+=(
-        "-DOT_PLATFORM=cc2652"
-        "-DCMAKE_TOOLCHAIN_FILE=examples/platforms/cc2652/arm-none-eabi.cmake"
-        "-DOT_COMMISSIONER=on"
-        "-DOT_DHCP6_CLIENT=on"
-        "-DOT_DHCP6_SERVER=on"
-        "-DOT_DNS_CLIENT=on"
-        "-DOT_JOINER=on"
-        "-DOT_SLAAC=on"
-        "-DCMAKE_BUILD_TYPE=Release"
-    )
+    local options=("${OT_COMMON_OPTIONS[@]}"
+                   "${OT_BASIC_CHECK_OPTIONS[@]}")
 
     reset_source
-    mkdir -p "$OT_BUILDDIR"
-    cd "$OT_BUILDDIR"
-    cmake -GNinja "${options[@]}" ..
-    ninja
-    cd "$OT_SRCDIR"
+    "$(dirname "$0")"/cmake-build cc2652 "${options[@]}"
 }
 
 build_kw41z()
 {
-    local options=("${OT_COMMON_OPTIONS[@]}")
-
-    options+=(
-        "-DOT_PLATFORM=kw41z"
-        "-DCMAKE_TOOLCHAIN_FILE=examples/platforms/kw41z/arm-none-eabi.cmake"
-        "-DOT_COMMISSIONER=on"
-        "-DOT_DHCP6_CLIENT=on"
-        "-DOT_DHCP6_SERVER=on"
-        "-DOT_DNS_CLIENT=on"
-        "-DOT_JOINER=on"
-        "-DOT_SLAAC=on"
-        "-DCMAKE_BUILD_TYPE=Release"
-    )
+    local options=("${OT_COMMON_OPTIONS[@]}"
+                   "${OT_BASIC_CHECK_OPTIONS[@]}")
 
     reset_source
-    mkdir -p "$OT_BUILDDIR"
-    cd "$OT_BUILDDIR"
-    cmake -GNinja "${options[@]}" ..
-    ninja
-    cd "$OT_SRCDIR"
+    "$(dirname "$0")"/cmake-build kw41z "${options[@]}"
 }
 
 build_qpg6095()
 {
-    local options=("${OT_COMMON_OPTIONS[@]}")
-
-    options+=(
-        "-DOT_PLATFORM=qpg6095"
-        "-DCMAKE_TOOLCHAIN_FILE=examples/platforms/qpg6095/arm-none-eabi.cmake"
-        "-DOT_COMMISSIONER=on"
-        "-DOT_DHCP6_CLIENT=on"
-        "-DOT_DHCP6_SERVER=on"
-        "-DOT_DNS_CLIENT=on"
-        "-DOT_JOINER=on"
-        "-DOT_SLAAC=on"
-        "-DCMAKE_BUILD_TYPE=Release"
-    )
+    local options=("${OT_COMMON_OPTIONS[@]}"
+                   "${OT_BASIC_CHECK_OPTIONS[@]}")
 
     reset_source
-    mkdir -p "$OT_BUILDDIR"
-    cd "$OT_BUILDDIR"
-    cmake -GNinja "${options[@]}" ..
-    ninja
-    cd "$OT_SRCDIR"
+    "$(dirname "$0")"/cmake-build qpg6095 "${options[@]}"
 }
 
 build_samr21()
 {
-    local options=("${OT_COMMON_OPTIONS[@]}")
-
-    options+=(
-        "-DOT_PLATFORM=samr21"
-        "-DCMAKE_TOOLCHAIN_FILE=examples/platforms/samr21/arm-none-eabi.cmake"
-        "-DOT_COMMISSIONER=on"
-        "-DOT_DHCP6_CLIENT=on"
-        "-DOT_DHCP6_SERVER=on"
-        "-DOT_DNS_CLIENT=on"
-        "-DOT_JOINER=on"
-        "-DOT_SLAAC=on"
-        "-DCMAKE_BUILD_TYPE=Release"
-    )
+    local options=("${OT_COMMON_OPTIONS[@]}"
+                   "${OT_BASIC_CHECK_OPTIONS[@]}")
 
     reset_source
-    wget http://ww1.microchip.com/downloads/en/DeviceDoc/asf-standalone-archive-3.45.0.85.zip || die
-    unzip -qq asf-standalone-archive-3.45.0.85.zip || die
-    mv xdk-asf-3.45.0 third_party/microchip/asf || die
-    mkdir -p "$OT_BUILDDIR"
-    cd "$OT_BUILDDIR"
-    cmake -GNinja "${options[@]}" ..
-    ninja
-    cd "$OT_SRCDIR"
+
+    asfzip=asf-standalone-archive-3.45.0.85.zip
+    wget http://ww1.microchip.com/downloads/en/DeviceDoc/${asfzip} || die "Download ${asfzip} failed"
+    unzip -qq ${asfzip} || die "Unzip ${asfzip} failed."
+    mv xdk-asf-3.45.0 third_party/microchip/asf || die "Move xdk-asf-3.45.0 failed."
+
+    "$(dirname "$0")"/cmake-build samr21 "${options[@]}"
 }
 
 main()
diff --git a/script/cmake-build b/script/cmake-build
--- a/script/cmake-build
+++ b/script/cmake-build
@@ -1,3 +1,4 @@
+#!/bin/bash
 #
 #  Copyright (c) 2020, The OpenThread Authors.
 #  All rights reserved.
@@ -26,26 +27,57 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #
 
-set(CMAKE_SYSTEM_NAME              Generic)
-set(CMAKE_SYSTEM_PROCESSOR         ARM)
-set(CMAKE_BUILD_TYPE               Release CACHE STRING "Set build type to release to save memory")
+set -euo pipefail
 
-set(CMAKE_C_COMPILER               arm-none-eabi-gcc)
-set(CMAKE_CXX_COMPILER             arm-none-eabi-g++)
-set(CMAKE_ASM_COMPILER             arm-none-eabi-as)
-set(CMAKE_RANLIB                   arm-none-eabi-ranlib)
+readonly OT_PLATFORMS=(cc1352 cc2538 cc2650 cc2652 kw41z qpg6095 samr21 simulation posix)
 
-set(COMMON_C_FLAGS                 "-mcpu=cortex-m4 -mthumb -fdata-sections -ffunction-sections")
+die()
+{
+    echo " ** ERROR: Openthread cmake doesn't support platform \"$1\""
+    exit 1
+}
 
-set(CMAKE_C_FLAGS                  "${COMMON_C_FLAGS} -std=gnu99")
-set(CMAKE_CXX_FLAGS                "${COMMON_C_FLAGS} -fno-exceptions -fno-rtti")
-set(CMAKE_ASM_FLAGS                "${COMMON_C_FLAGS}")
-set(CMAKE_EXE_LINKER_FLAGS_INIT    "${COMMON_C_FLAGS} -specs=nano.specs -specs=nosys.specs")
+build()
+{
+    platform=$1
+    options=($2)
+    targets=($3)
 
-set(CMAKE_C_FLAGS_DEBUG            "-Og -g")
-set(CMAKE_CXX_FLAGS_DEBUG          "-Og -g")
-set(CMAKE_ASM_FLAGS_DEBUG          "-g")
+    mkdir -p build/${platform}
+    cd build/${platform}
+    cmake -GNinja ${options[*]} ../..
+    ninja ${targets[*]}
+    cd ../..
+}
 
-set(CMAKE_C_FLAGS_RELEASE          "-Os")
-set(CMAKE_CXX_FLAGS_RELEASE        "-Os")
-set(CMAKE_ASM_FLAGS_RELEASE        "")
+main()
+{
+    if [[ $# == 0 ]]; then
+        >&2 echo "Please select a platform: ${OT_PLATFORMS[*]}"
+        # 128 for Invalid arguments
+        exit 128
+    fi
+
+    local targets=()
+    local platform="$1"
+    shift
+    local options=(
+        "-DOT_PLATFORM=${platform}"
+        "$@"
+    )
+
+    # Check if the platform supports cmake.
+    echo "${OT_PLATFORMS[@]}" | grep -wq "${platform}" || die ${platform}
+
+    if [[ "${platform}" != "posix" ]] && [[ "${platform}" != "simulation" ]]; then
+        options+=("-DCMAKE_TOOLCHAIN_FILE=examples/platforms/${platform}/arm-none-eabi.cmake")
+    fi
+
+    if [[ "${platform}" == "cc2650" ]]; then
+        targets+=("ot-cli-mtd" "ot-ncp-mtd")
+    fi
+
+    build "${platform}" "${options[*]}" "${targets[*]}"
+}
+
+main "$@"
