add another ot-daemon node and expect it to become Router

diff --git a/script/check-posix-pty b/script/check-posix-pty
--- a/script/check-posix-pty
+++ b/script/check-posix-pty
@@ -139,6 +139,33 @@ EOF
         fi
     done
 
+    # add another node as a Router
+    RADIO_URL2="spinel+hdlc+uart://${RADIO_NCP_PATH}?forkpty-arg=2"
+    readonly VALID_NETIF_NAME2="wan$(date +%H%M%S)"
+    if [[ ${DAEMON} == 1 ]]; then
+        sudo "$(pwd)/$(ls output/posix/*linux*/bin/ot-daemon)" -I "${VALID_NETIF_NAME2}" "${RADIO_URL2}" &
+        sleep 1
+        OT_CLI_ARGS2=(-I "${VALID_NETIF_NAME2}")
+        sudo "${OT_CLI_CMD}" "${OT_CLI_ARGS2[@]}" panid 0xface | grep 'Done' || die 'failed to set panid with ot-ctl'
+    else
+        sudo "${OT_CLI}" -I "${VALID_NETIF_NAME2}" -n "${RADIO_URL2}"
+    fi
+
+    sudo expect <<EOF |
+spawn ${OT_CLI_CMD} ${OT_CLI_ARGS2[@]}
+send "panid 0xface\r\n"
+expect "Done"
+send "ifconfig up\r\n"
+expect "Done"
+send "thread start\r\n"
+expect "Done"
+sleep 10
+send "state\r\n"
+expect "router"
+expect "Done"
+wait
+EOF
+
     netstat -an | grep -q 61631 || die 'TMF port is not available!'
 
     extaddr=$(awk '/extaddr/{getline; print}' $OT_OUTPUT | tr -d '\r\n')
