[scripts] apply shfmt and shellharden changes

diff --git a/script/check-posix-pty b/script/check-posix-pty
--- a/script/check-posix-pty
+++ b/script/check-posix-pty
@@ -30,12 +30,14 @@
 set -e
 set -x
 
-die() {
-	echo " *** ERROR: " $*
-	exit 1
+die()
+{
+    echo " *** ERROR: " "$@"
+    exit 1
 }
 
-at_exit() {
+at_exit()
+{
     EXIT_CODE=$?
 
     sudo killall expect || true
@@ -43,59 +45,65 @@ at_exit() {
     killall ot-daemon || true
     killall socat || true
 
-    exit $EXIT_CODE
+    exit "$EXIT_CODE"
 }
 
-build() {
+build()
+{
     make -f examples/Makefile-simulation
     make -f src/posix/Makefile-posix PLATFORM_NETIF=1 PLATFORM_UDP=1 UDP_FORWARD=0
 }
 
-check() {
+check()
+{
     trap at_exit INT TERM EXIT
 
     SOCAT_OUTPUT=/tmp/ot-socat
     OT_OUTPUT=/tmp/ot-output
-    socat -d -d pty,raw,echo=0 pty,raw,echo=0 > /dev/null 2> $SOCAT_OUTPUT &
+    socat -d -d pty,raw,echo=0 pty,raw,echo=0 >/dev/null 2>"$SOCAT_OUTPUT" &
     while true; do
-        if test $(head -n2 $SOCAT_OUTPUT | wc -l) = 2; then
-            RADIO_PTY=$(head -n1 $SOCAT_OUTPUT | grep -o '/dev/.\+')
-            CORE_PTY=$(head -n2 $SOCAT_OUTPUT | tail -n1 | grep -o '/dev/.\+')
+        if test "$(head -n2 "$SOCAT_OUTPUT" | wc -l)" = 2; then
+            RADIO_PTY=$(head -n1 "$SOCAT_OUTPUT" | grep -o '/dev/.\+')
+            CORE_PTY=$(head -n2 "$SOCAT_OUTPUT" | tail -n1 | grep -o '/dev/.\+')
             break
         fi
         echo 'Waiting for socat ready...'
         sleep 1
     done
-    echo 'RADIO_PTY' $DEVICE_PTY
-    echo 'CORE_PTY' $CORE_PTY
+    echo 'RADIO_PTY' "$DEVICE_PTY"
+    echo 'CORE_PTY' "$CORE_PTY"
 
-    RADIO_NCP_PATH="$(pwd)/$(ls output/*linux*/bin/ot-rcp)"
-    $RADIO_NCP_PATH 1 > $RADIO_PTY < $RADIO_PTY &
+    RADIO_NCP_PATH="$PWD/$(ls output/*linux*/bin/ot-rcp)"
+
+    # shellcheck disable=SC2094
+    "$RADIO_NCP_PATH" 1 >"$RADIO_PTY" <"$RADIO_PTY" &
 
     # Cover setting a valid network interface name.
     readonly VALID_NETIF_NAME="wan$(date +%H%M%S)"
 
-    if [[ "${DAEMON}" = 1 ]]; then
-        sudo "$(pwd)/$(ls output/posix/*linux*/bin/ot-daemon)" -I "${VALID_NETIF_NAME}" ${CORE_PTY} &
+    if [[ ${DAEMON} == 1 ]]; then
+        sudo "$PWD/$(ls output/posix/*linux*/bin/ot-daemon)" -I "$VALID_NETIF_NAME" "$CORE_PTY" &
         sleep 1
-        OT_CLI_CMD="$(pwd)/$(ls output/posix/*linux*/bin/ot-ctl)"
+        OT_CLI_CMD="$PWD/$(ls output/posix/*linux*/bin/ot-ctl)"
+        OT_CLI_ARG=
     else
-        OT_CLI_CMD="$(pwd)/$(ls output/posix/*linux*/bin/ot-cli) ${CORE_PTY}"
+        OT_CLI_CMD="$PWD/$(ls output/posix/*linux*/bin/ot-cli)"
+        OT_CLI_ARG="$CORE_PTY"
     fi
 
-    sudo ${OT_CLI_CMD} -I "${VALID_NETIF_NAME}" -n
+    sudo "$OT_CLI_CMD" "$OT_CLI_ARG" -I "$VALID_NETIF_NAME" -n
 
     # Cover setting a too long(max is 15 characters) network interface name.
     # Expect exit code to be 2(OT_EXIT_INVALID_ARGUMENTS).
     readonly INVALID_NETIF_NAME="wan0123456789123"
-    sudo ${OT_CLI_CMD} -I "${INVALID_NETIF_NAME}" -n || test $? = 2
+    sudo "$OT_CLI_CMD" "$OT_CLI_ARG" -I "$INVALID_NETIF_NAME" -n || test $? = 2
 
-    if [[ "${DAEMON}" = 1 ]]; then
-        sudo ${OT_CLI_CMD} panid 0xface | grep 'Done' || die 'failed to set panid with ot-ctl'
+    if [[ ${DAEMON} == 1 ]]; then
+        sudo "$OT_CLI_CMD" "$OT_CLI_ARG" panid 0xface | grep 'Done' || die 'failed to set panid with ot-ctl'
     fi
 
-    sudo expect <<EOF > "${OT_OUTPUT}" &
-spawn ${OT_CLI_CMD}
+    sudo expect <<EOF | tee "${OT_OUTPUT}" &
+spawn ${OT_CLI_CMD} ${OT_CLI_ARG}
 send "panid 0xface\r\n"
 expect "Done"
 send "ifconfig up\r\n"
@@ -118,7 +126,7 @@ EOF
     # wait until the node becomes leader
     while true; do
         sleep 5
-        if grep -q leader $OT_OUTPUT; then
+        if grep -q leader "$OT_OUTPUT"; then
             break
         else
             echo 'Still waiting for leader'
@@ -127,28 +135,33 @@ EOF
 
     netstat -an | grep -q 61631 || die 'TMF port is not available!'
 
-    extaddr=$(awk '/extaddr/{getline; print}' $OT_OUTPUT | tr -d '\r\n')
-    echo "Extended address is: ${extaddr}"
+    extaddr=$(awk '/extaddr/{getline; print}' "$OT_OUTPUT" | tr -d '\r\n')
+    echo "Extended address is: $extaddr"
 
-    if [[ "${DAEMON}" = 1 ]]; then
+    if [[ ${DAEMON} == 1 ]]; then
         sudo killall -9 expect || true
         sudo killall -9 ot-ctl || true
-        NETIF_INDEX=$(ip link show "${VALID_NETIF_NAME}" | cut -f 1 -d ":" | head -n 1)
-        sudo PATH="$(dirname ${OT_CLI_CMD}):${PATH}" \
-             python3 "$PWD/tests/scripts/misc/test_multicast_join.py" "${NETIF_INDEX}" \
-             || die 'multicast group join failed'
+        NETIF_INDEX=$(ip link show "$VALID_NETIF_NAME" | cut -f 1 -d ":" | head -n 1)
+        sudo PATH="$(dirname "$OT_CLI_CMD"):$PATH" \
+            python3 "$PWD/tests/scripts/misc/test_multicast_join.py" "$NETIF_INDEX" \
+            || die 'multicast group join failed'
     fi
 
     LEADER_ALOC=fdde:ad00:beef::ff:fe00:fc00
     # Retrievie extended address through network diagnostic get
-    coap_response=$(echo -n '120100' | xxd -r -p | coap-client -m POST coap://[${LEADER_ALOC}]:61631/d/dg -f- | xxd -p | grep 0008)
-    echo "CoAP response is: ${coap_response}"
+    coap_response=$(echo -n '120100' | xxd -r -p | coap-client -m POST coap://["$LEADER_ALOC"]:61631/d/dg -f- | xxd -p | grep 0008)
+    echo "CoAP response is: $coap_response"
 
     # Verify CoAP response contains the extended address
-    [[ "${coap_response}" = *${extaddr}* ]] && echo 'Success' || die 'failed to get extended address'
+    if [[ ${coap_response} == *${extaddr}* ]]; then
+        echo 'Success'
+    else
+        die 'failed to get extended address'
+    fi
 }
 
-main() {
+main()
+{
     case $1 in
         build)
             build
diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -32,8 +32,8 @@
 
 set -euo pipefail
 
-readonly OT_BUILDDIR="$(pwd)/build"
-readonly OT_SRCDIR="$(pwd)"
+readonly OT_BUILDDIR="$PWD/build"
+readonly OT_SRCDIR="$PWD"
 readonly OT_TEST_COMMON_OPTIONS=(
     "-DOT_BORDER_AGENT=ON"
     "-DOT_BORDER_ROUTER=ON"
@@ -74,36 +74,36 @@ build_simulation()
 
     options+=(
         "-DOT_PLATFORM=simulation"
-        "-DOT_THREAD_VERSION=${version}"
+        "-DOT_THREAD_VERSION=$version"
     )
 
-    if [[ "${VIRTUAL_TIME}" == 1 ]]; then
+    if [[ ${VIRTUAL_TIME} == 1 ]]; then
         options+=("-DOT_SIMULATION_VIRTUAL_TIME=ON")
 
-        if [[ "${NODE_MODE}" == "rcp" ]]; then
+        if [[ ${NODE_MODE} == "rcp" ]]; then
             options+=("-DOT_SIMULATION_VIRTUAL_TIME_UART=ON")
         fi
 
     fi
 
-    local builddir="${OT_BUILDDIR}/cmake/openthread-simulation-${version}"
-    (mkdir -p "${builddir}" \
-        && cd "${builddir}" \
-        && cmake -GNinja "${OT_SRCDIR}" "${options[@]}" \
+    local builddir="$OT_BUILDDIR/cmake/openthread-simulation-$version"
+    (mkdir -p "$builddir" \
+        && cd "$builddir" \
+        && cmake -GNinja "$OT_SRCDIR" "${options[@]}" \
         && ninja)
 
-    if [[ "${version}" == "1.2" ]]; then
+    if [[ ${version} == "1.2" ]]; then
 
         options+=(
-        "-DOT_BACKBONE_ROUTER=ON"
-        "-DOT_BORDER_ROUTER=ON"
-        "-DOT_SERVICE=ON"
+            "-DOT_BACKBONE_ROUTER=ON"
+            "-DOT_BORDER_ROUTER=ON"
+            "-DOT_SERVICE=ON"
         )
 
-        local builddir="${OT_BUILDDIR}/cmake/openthread-simulation-${version}-bbr"
-        (mkdir -p "${builddir}" \
-            && cd "${builddir}" \
-            && cmake -GNinja "${OT_SRCDIR}" "${options[@]}" \
+        local builddir="$OT_BUILDDIR/cmake/openthread-simulation-$version-bbr"
+        (mkdir -p "$builddir" \
+            && cd "$builddir" \
+            && cmake -GNinja "$OT_SRCDIR" "${options[@]}" \
             && ninja)
 
     fi
@@ -117,85 +117,90 @@ build_posix()
     options+=(
         "-DOT_PLATFORM=posix"
         "-DOT_READLINE=readline"
-        "-DOT_THREAD_VERSION=${version}"
+        "-DOT_THREAD_VERSION=$version"
     )
 
-    if [[ "${VIRTUAL_TIME}" == 1 ]]; then
+    if [[ ${VIRTUAL_TIME} == 1 ]]; then
         options+=("-DOT_POSIX_VIRTUAL_TIME=ON")
     fi
 
-    local builddir="${OT_BUILDDIR}/cmake/openthread-posix-${version}"
-    (mkdir -p "${builddir}" \
-        && cd "${builddir}" \
-        && cmake -GNinja "${OT_SRCDIR}" "${options[@]}" \
+    local builddir="$OT_BUILDDIR/cmake/openthread-posix-$version"
+    (mkdir -p "$builddir" \
+        && cd "$builddir" \
+        && cmake -GNinja "$OT_SRCDIR" "${options[@]}" \
         && ninja)
 
-    if [[ "${version}" == "1.2" ]]; then
+    if [[ ${version} == "1.2" ]]; then
 
         options+=(
-        "-DOT_BACKBONE_ROUTER=ON"
-        "-DOT_BORDER_ROUTER=ON"
-        "-DOT_SERVICE=ON"
+            "-DOT_BACKBONE_ROUTER=ON"
+            "-DOT_BORDER_ROUTER=ON"
+            "-DOT_SERVICE=ON"
         )
 
-        local builddir="${OT_BUILDDIR}/cmake/openthread-posix-${version}-bbr"
-        (mkdir -p "${builddir}" \
-            && cd "${builddir}" \
-            && cmake -GNinja "${OT_SRCDIR}" "${options[@]}" \
+        local builddir="$OT_BUILDDIR/cmake/openthread-posix-$version-bbr"
+        (mkdir -p "$builddir" \
+            && cd "$builddir" \
+            && cmake -GNinja "$OT_SRCDIR" "${options[@]}" \
             && ninja)
     fi
 }
 
-do_build() {
-    build_simulation "${THREAD_VERSION}"
+do_build()
+{
+    build_simulation "$THREAD_VERSION"
 
-    if [[ "${NODE_MODE}" == "rcp" ]]; then
-        build_posix "${THREAD_VERSION}"
+    if [[ ${NODE_MODE} == "rcp" ]]; then
+        build_posix "$THREAD_VERSION"
     fi
 
     # Extra 1.1 build for 1.2 tests
-    if [[ "${THREAD_VERSION}" == "1.2" ]]; then
+    if [[ ${THREAD_VERSION} == "1.2" ]]; then
         build_simulation 1.1
 
-        if [[ "${NODE_MODE}" == "rcp" ]]; then
+        if [[ ${NODE_MODE} == "rcp" ]]; then
             build_posix 1.1
         fi
     fi
 }
 
-do_clean() {
-    rm -rfv "${OT_BUILDDIR}"
+do_clean()
+{
+    rm -rfv "$OT_BUILDDIR"
 }
 
-do_unit() {
-    local builddir="${OT_BUILDDIR}/cmake/openthread-simulation-${THREAD_VERSION}"
-    if [[ ! -d "${builddir}" ]]; then
+do_unit()
+{
+    local builddir="$OT_BUILDDIR/cmake/openthread-simulation-$THREAD_VERSION"
+    if [[ ! -d ${builddir} ]]; then
         echo "Cannot find build directory!"
-        exit -1
+        exit 1
     fi
 
-    cd "${builddir}"
+    cd "$builddir"
     ninja test
 }
 
-do_cert() {
-    export top_builddir="${OT_BUILDDIR}/cmake/openthread-simulation-${THREAD_VERSION}"
+do_cert()
+{
+    export top_builddir="$OT_BUILDDIR/cmake/openthread-simulation-$THREAD_VERSION"
 
-    if [[ "${THREAD_VERSION}" == "1.2" ]]; then
-        export top_builddir_1_1="${OT_BUILDDIR}/cmake/openthread-simulation-1.1"
-        export top_builddir_1_2_bbr="${OT_BUILDDIR}/cmake/openthread-simulation-1.2-bbr"
+    if [[ ${THREAD_VERSION} == "1.2" ]]; then
+        export top_builddir_1_1="$OT_BUILDDIR/cmake/openthread-simulation-1.1"
+        export top_builddir_1_2_bbr="$OT_BUILDDIR/cmake/openthread-simulation-1.2-bbr"
     fi
 
     [[ ! -d tmp ]] || rm -rvf tmp
     PYTHONUNBUFFERED=1 "$1"
 }
 
-do_cert_suite() {
-    export top_builddir="${OT_BUILDDIR}/cmake/openthread-simulation-${THREAD_VERSION}"
+do_cert_suite()
+{
+    export top_builddir="$OT_BUILDDIR/cmake/openthread-simulation-$THREAD_VERSION"
 
-    if [[ "${THREAD_VERSION}" == "1.2" ]]; then
-        export top_builddir_1_1="${OT_BUILDDIR}/cmake/openthread-simulation-1.1"
-        export top_builddir_1_2_bbr="${OT_BUILDDIR}/cmake/openthread-simulation-1.2-bbr"
+    if [[ ${THREAD_VERSION} == "1.2" ]]; then
+        export top_builddir_1_1="$OT_BUILDDIR/cmake/openthread-simulation-1.1"
+        export top_builddir_1_2_bbr="$OT_BUILDDIR/cmake/openthread-simulation-1.2-bbr"
     fi
 
     local pass_count=0
@@ -205,18 +210,18 @@ do_cert_suite() {
 
     for test_case in "$@"; do
         rm -rf tmp
-        if "${test_case}" &> test.log; then
-            echo -e "${COLOR_PASS}PASS${COLOR_NONE} ${test_case}"
-            pass_count=$(( pass_count + 1 ))
+        if "$test_case" &>test.log; then
+            echo -e "${COLOR_PASS}PASS$COLOR_NONE $test_case"
+            pass_count=$((pass_count + 1))
         else
-            echo -e "${COLOR_FAIL}FAIL${COLOR_NONE} ${test_case}"
-            fail_count=$(( fail_count + 1 ))
+            echo -e "${COLOR_FAIL}FAIL$COLOR_NONE $test_case"
+            fail_count=$((fail_count + 1))
             {
                 echo "=============================="
-                echo "!!! FAIL:${test_case}"
+                echo "!!! FAIL:$test_case"
                 echo "=============================="
                 cat test.log
-            } >> fail.log
+            } >>fail.log
         fi
     done
 
@@ -224,11 +229,11 @@ do_cert_suite() {
     echo "         Test Summary"
     echo "=================================="
     echo "# TOTAL: $((pass_count + fail_count))"
-    echo "# PASS: ${pass_count}"
-    echo "# FAIL: ${fail_count}"
+    echo "# PASS: $pass_count"
+    echo "# FAIL: $fail_count"
 
-    if [[ "${fail_count}" -gt 0 ]]; then
-        tr -dc '[:print:]\r\n\t' < fail.log
+    if [[ ${fail_count} -gt 0 ]]; then
+        tr -dc '[:print:]\r\n\t' <fail.log
         exit 1
     else
         exit 0
@@ -239,23 +244,23 @@ do_expect()
 {
     local ot_command
 
-    if [[ "${NODE_MODE}" == rcp ]]; then
-        ot_command="${OT_CLI_PATH} ${RADIO_DEVICE}"
+    if [[ ${NODE_MODE} == rcp ]]; then
+        ot_command="$OT_CLI_PATH $RADIO_DEVICE"
     else
-        ot_command="${OT_BUILDDIR}/cmake/openthread-simulation-${THREAD_VERSION}/examples/apps/cli/ot-cli-ftd"
+        ot_command="$OT_BUILDDIR/cmake/openthread-simulation-$THREAD_VERSION/examples/apps/cli/ot-cli-ftd"
     fi
 
     while read -r script; do
         rm -rf tmp
-        OT_COMMAND="${ot_command}" "${script}" || {
+        OT_COMMAND="$ot_command" "$script" || {
             local exit_code=$?
-            echo -e "${COLOR_FAIL}FAIL${COLOR_NONE} ${script}"
-            exit "${exit_code}"
+            echo -e "${COLOR_FAIL}FAIL$COLOR_NONE $script"
+            exit "$exit_code"
         }
-        echo -e "${COLOR_PASS}PASS${COLOR_NONE} ${script}"
+        echo -e "${COLOR_PASS}PASS$COLOR_NONE $script"
     done < <(
         if [[ $# != 0 ]]; then
-            for script in "$@"; do echo ${script}; done
+            for script in "$@"; do echo "$script"; done
         else
             find tests/scripts/expect -type f -executable
         fi
@@ -264,7 +269,8 @@ do_expect()
     exit 0
 }
 
-print_usage() {
+print_usage()
+{
     echo "USAGE: [ENVIRONMENTS] $0 COMMANDS
 
 ENVIRONMENTS:
@@ -314,8 +320,9 @@ EXAMPLES:
     exit "$1"
 }
 
-do_package() {
-    local builddir="${OT_BUILDDIR}/cmake/openthread-sim"
+do_package()
+{
+    local builddir="$OT_BUILDDIR/cmake/openthread-sim"
     local options=(
         "-DOT_BORDER_AGENT=ON"
         "-DOT_BORDER_ROUTER=ON"
@@ -330,48 +337,48 @@ do_package() {
         "-DOT_SERVICE=ON"
         "-DOT_SLAAC=ON"
     )
-    (mkdir -p "${builddir}" \
-        && cd "${builddir}" \
-        && cmake -GNinja "${OT_SRCDIR}" -DOT_PLATFORM="simulation" "${options[@]}" \
+    (mkdir -p "$builddir" \
+        && cd "$builddir" \
+        && cmake -GNinja "$OT_SRCDIR" -DOT_PLATFORM="simulation" "${options[@]}" \
         && ninja package \
-        && ls "${builddir}"/openthread-simulation-*.deb)
+        && ls "$builddir"/openthread-simulation-*.deb)
 
-    builddir="${OT_BUILDDIR}/cmake/openthread-host"
-    (mkdir -p "${builddir}" \
-        && cd "${builddir}" \
-        && cmake -GNinja "${OT_SRCDIR}" -DOT_PLATFORM="posix" "${options[@]}" \
+    builddir="$OT_BUILDDIR/cmake/openthread-host"
+    (mkdir -p "$builddir" \
+        && cd "$builddir" \
+        && cmake -GNinja "$OT_SRCDIR" -DOT_PLATFORM="posix" "${options[@]}" \
         && ninja package \
-        && ls "${builddir}"/openthread-standalone-*.deb)
+        && ls "$builddir"/openthread-standalone-*.deb)
 
-    builddir="${OT_BUILDDIR}/cmake/openthread-daemon"
-    (mkdir -p "${builddir}" \
-        && cd "${builddir}" \
-        && cmake -GNinja "${OT_SRCDIR}" -DOT_PLATFORM="posix" \
-        -DOT_DAEMON=1 -DOT_PLATFORM_NETIF=1 -DOT_PLATFORM_UDP=1 "${options[@]}" \
+    builddir="$OT_BUILDDIR/cmake/openthread-daemon"
+    (mkdir -p "$builddir" \
+        && cd "$builddir" \
+        && cmake -GNinja "$OT_SRCDIR" -DOT_PLATFORM="posix" \
+            -DOT_DAEMON=1 -DOT_PLATFORM_NETIF=1 -DOT_PLATFORM_UDP=1 "${options[@]}" \
         && ninja package \
-        && ls "${builddir}"/openthread-daemon-*.deb)
+        && ls "$builddir"/openthread-daemon-*.deb)
 }
 
 envsetup()
 {
-    if [[ "${NODE_MODE}" == 'rcp' ]] ; then
-        export RADIO_DEVICE="${OT_BUILDDIR}/cmake/openthread-simulation-${THREAD_VERSION}/examples/apps/ncp/ot-rcp"
-        export OT_CLI_PATH="${OT_BUILDDIR}/cmake/openthread-posix-${THREAD_VERSION}/src/posix/ot-cli"
-        export OT_NCP_PATH="${OT_BUILDDIR}/cmake/openthread-posix-${THREAD_VERSION}/src/posix/ot-ncp"
+    if [[ ${NODE_MODE} == 'rcp' ]]; then
+        export RADIO_DEVICE="$OT_BUILDDIR/cmake/openthread-simulation-$THREAD_VERSION/examples/apps/ncp/ot-rcp"
+        export OT_CLI_PATH="$OT_BUILDDIR/cmake/openthread-posix-$THREAD_VERSION/src/posix/ot-cli"
+        export OT_NCP_PATH="$OT_BUILDDIR/cmake/openthread-posix-$THREAD_VERSION/src/posix/ot-ncp"
 
-        if [[ "${THREAD_VERSION}" == "1.2" ]]; then
-            export RADIO_DEVICE_1_1="${OT_BUILDDIR}/cmake/openthread-simulation-1.1/examples/apps/ncp/ot-rcp"
-            export OT_CLI_PATH_1_1="${OT_BUILDDIR}/cmake/openthread-posix-1.1/src/posix/ot-cli"
-            export OT_NCP_PATH_1_1="${OT_BUILDDIR}/cmake/openthread-posix-1.1/src/posix/ot-ncp"
-            export OT_CLI_PATH_1_2_BBR="${OT_BUILDDIR}/cmake/openthread-posix-1.2-bbr/src/posix/ot-cli"
-            export OT_NCP_PATH_1_2_BBR="${OT_BUILDDIR}/cmake/openthread-posix-1.2-bbr/src/posix/ot-ncp"
+        if [[ ${THREAD_VERSION} == "1.2" ]]; then
+            export RADIO_DEVICE_1_1="$OT_BUILDDIR/cmake/openthread-simulation-1.1/examples/apps/ncp/ot-rcp"
+            export OT_CLI_PATH_1_1="$OT_BUILDDIR/cmake/openthread-posix-1.1/src/posix/ot-cli"
+            export OT_NCP_PATH_1_1="$OT_BUILDDIR/cmake/openthread-posix-1.1/src/posix/ot-ncp"
+            export OT_CLI_PATH_1_2_BBR="$OT_BUILDDIR/cmake/openthread-posix-1.2-bbr/src/posix/ot-cli"
+            export OT_NCP_PATH_1_2_BBR="$OT_BUILDDIR/cmake/openthread-posix-1.2-bbr/src/posix/ot-ncp"
         fi
     fi
 
     export NODE_TYPE VIRTUAL_TIME
 
     # CMake always works in verbose mode if VERBOSE exists in environments.
-    if [[ "${VERBOSE}" == 1 ]]; then
+    if [[ ${VERBOSE} == 1 ]]; then
         export VERBOSE
     else
         export -n VERBOSE
@@ -382,14 +389,14 @@ main()
 {
     envsetup
 
-    if [[ -z "$1" ]]; then
+    if [[ -z $1 ]]; then
         print_usage 1
     fi
 
-    [[ "${NODE_MODE}" == "rcp" ]] && echo "Using rcp mode" || echo "Using standalone mode"
-    [[ "${NODE_TYPE}" == "ncp-sim" ]] && echo "Using NCP node" || echo "Using CLI node"
-    [[ "${VIRTUAL_TIME}" == 1 ]] && echo "Using virtual time" || echo "Using real time"
-    [[ "${THREAD_VERSION}" == "1.2" ]] && echo "Using Thread 1.2 stack" || echo "Using Thread 1.1 stack"
+    [[ ${NODE_MODE} == "rcp" ]] && echo "Using rcp mode" || echo "Using standalone mode"
+    [[ ${NODE_TYPE} == "ncp-sim" ]] && echo "Using NCP node" || echo "Using CLI node"
+    [[ ${VIRTUAL_TIME} == 1 ]] && echo "Using virtual time" || echo "Using real time"
+    [[ ${THREAD_VERSION} == "1.2" ]] && echo "Using Thread 1.2 stack" || echo "Using Thread 1.1 stack"
 
     while [[ $# != 0 ]]; do
         case "$1" in
