fix check-posix-pty

diff --git a/script/check-posix-pty b/script/check-posix-pty
--- a/script/check-posix-pty
+++ b/script/check-posix-pty
@@ -86,14 +86,14 @@ check()
     if [[ ${DAEMON} == 1 ]]; then
         sudo "$(pwd)/$(ls output/posix/*linux*/bin/ot-daemon)" -I "${VALID_NETIF_NAME}" "${RADIO_URL}" &
         sleep 1
-        OT_CLI_CMD="$(pwd)/$(ls output/posix/*linux*/bin/ot-ctl)"
-        sudo "${OT_CLI_CMD}" -I "${VALID_NETIF_NAME}" panid 0xface | grep 'Done' || die 'failed to set panid with ot-ctl'
+        OT_CLI_CMD="$(pwd)/$(ls output/posix/*linux*/bin/ot-ctl)" -I "${VALID_NETIF_NAME}"
+        sudo "${OT_CLI_CMD}" panid 0xface | grep 'Done' || die 'failed to set panid with ot-ctl'
 
         # verify this reset and factoryreset end immediately
-        sudo "${OT_CLI_CMD}" -I "${VALID_NETIF_NAME}" reset
+        sudo "${OT_CLI_CMD}" reset
         # sleep a while for daemon ready
         sleep 2
-        sudo "${OT_CLI_CMD}" -I "${VALID_NETIF_NAME}" factoryreset
+        sudo "${OT_CLI_CMD}" factoryreset
     else
         OT_CLI="$(pwd)/$(ls output/posix/*linux*/bin/ot-cli)"
         sudo "${OT_CLI}" -I "${VALID_NETIF_NAME}" -n "${RADIO_URL}"
