[posix] enable expect tests on macOS
This commit enables expect tests on macOS, also includes the following
required changes:

* Fixed bound to interface issue on macOS.
* Added ability to configure scan period, because macOS environment on
  GitHub Actions is much slower.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -37,6 +37,7 @@ readonly OT_SRCDIR="${PWD}"
 
 readonly COLOR_PASS='\033[0;32m'
 readonly COLOR_FAIL='\033[0;31m'
+readonly COLOR_SKIP='\033[0;33m'
 readonly COLOR_NONE='\033[0m'
 
 readonly OT_NODE_TYPE="${OT_NODE_TYPE:-cli}"
@@ -290,6 +291,43 @@ do_pktverify()
     python3 ./tests/scripts/thread-cert/pktverify/verify.py "$1"
 }
 
+ot_exec_expect_script()
+{
+    local log_file="tmp/log_expect"
+    local script="$1"
+
+    echo -e "\n${COLOR_PASS}EXEC${COLOR_NONE} ${script}"
+    sudo killall ot-rcp || true
+    sudo killall ot-cli || true
+    sudo killall ot-cli-ftd || true
+    sudo killall ot-cli-mtd || true
+    sudo rm -rf tmp
+    mkdir tmp
+    {
+        if [[ ${OT_NATIVE_IP} == 1 ]]; then
+            sudo -E expect -df "${script}" 2>"${log_file}"
+        else
+            expect -df "${script}" 2>"${log_file}"
+        fi
+    } || {
+        local EXIT_CODE=$?
+
+        # The exit status 77 for skipping is inherited from automake's test driver for script-based testsuites
+        if [[ ${EXIT_CODE} == 77 ]]; then
+            echo -e "\n${COLOR_SKIP}SKIP${COLOR_NONE} ${script}"
+            return 0
+        else
+            echo -e "\n${COLOR_FAIL}FAIL${COLOR_NONE} ${script}"
+            cat "${log_file}" >&2
+            return "${EXIT_CODE}"
+        fi
+    }
+    echo -e "\n${COLOR_PASS}PASS${COLOR_NONE} ${script}"
+    if [[ ${VERBOSE} == 1 ]]; then
+        cat "${log_file}" >&2
+    fi
+}
+
 do_expect()
 {
     local test_patterns
@@ -306,33 +344,13 @@ do_expect()
         test_patterns=(-name 'cli-*.exp' -o -name 'simulation-*.exp')
     fi
 
-    local log_file="tmp/log_expect"
-    while read -r script; do
-        sudo rm -rf tmp
-        mkdir tmp
-        {
-            if [[ ${OT_NATIVE_IP} == 1 ]]; then
-                sudo -E expect -df "${script}" 2>"${log_file}"
-            else
-                expect -df "${script}" 2>"${log_file}"
-            fi
-        } || {
-            local exit_code=$?
-            cat "${log_file}" >&2
-            echo -e "${COLOR_FAIL}FAIL${COLOR_NONE} ${script}"
-            exit "${exit_code}"
-        }
-        if [[ ${VERBOSE} == 1 ]]; then
-            cat "${log_file}" >&2
-        fi
-        echo -e "${COLOR_PASS}PASS${COLOR_NONE} ${script}"
-    done < <(
-        if [[ $# != 0 ]]; then
-            for script in "$@"; do echo ${script}; done
-        else
-            find tests/scripts/expect -type f -executable \( "${test_patterns[@]}" \)
-        fi
-    )
+    export -f ot_exec_expect_script
+
+    if [[ $# != 0 ]]; then
+        for script in "$@"; do bash -c "ot_exec_expect_script ${script}"; done
+    else
+        find tests/scripts/expect -type f -perm "$([[ $OSTYPE == darwin* ]] && echo '+' || echo '/')"111 \( "${test_patterns[@]}" \) -exec bash -c 'ot_exec_expect_script "$1"' _ {} \;
+    fi
 
     exit 0
 }
@@ -348,7 +366,8 @@ ENVIRONMENTS:
                     The default is 'cli'.
     OT_NATIVE_IP    1 to enable platform UDP and netif on POSIX platform. The default is 0.
     VERBOSE         1 to build or test verbosely. The default is 0.
-    VIRTUAL_TIME    1 for virtual time, otherwise real time. The default is 1.
+    VIRTUAL_TIME    1 for virtual time, otherwise real time. The default value is 0 when running expect tests,
+                    otherwise default value is 1.
     THREAD_VERSION  1.1 for Thread 1.1 stack, 1.2 for Thread 1.2 stack. The default is 1.1.
     INTER_OP        1 to build 1.1 together. Only works when THREAD_VERSION is 1.2. The default is 0.
     INTER_OP_BBR    1 to build bbr version together. Only works when THREAD_VERSION is 1.2. The default is 1.
